repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v2.0.4'
    hooks:
      - id: autopep8
        # autopep8 only takes one filename as argument unless the "--in-place" or "--diff" args are used
        args: [--max-line-length=120, --diff]
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args:
            - --max-line-length=120
  - repo: local
    hooks:
      - id: auto-requirements
        name: auto requirements
        entry: /bin/zsh ./hooks/auto-requirements.sh
        language: system
        pass_filenames: false
        always_run: true
